# Generated by Django 3.2.9 on 2021-12-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(default='default name', max_length=100),
        ),
    ]
