# Generated by Django 3.2.9 on 2021-12-31 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VOCDatasetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_file', models.FileField(upload_to='datasets/')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.imagemodel')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.taskmodel')),
            ],
        ),
    ]
