# Generated by Django 3.2.9 on 2021-12-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_imagemodel_name'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='end_date',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(default='RUNNING', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='images',
            field=models.ManyToManyField(blank=True, to='image.ImageModel'),
        ),
        migrations.CreateModel(
            name='COCODatasetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_file', models.FileField(upload_to='static/datasets')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.taskmodel')),
            ],
        ),
    ]
